config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :thoughts
  resources :relationships

  get '/sign_in', to: 'sessions#sign_in', as: 'sign_in'
  get '/sign_out', to: 'sessions#sign_out', as: 'sign_out'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'

  root 'thoughts#index'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :responder, class_name: "Thought"
  belongs_to :initiator, class_name: "Thought"
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/thought.rb
class Thought < ActiveRecord::Base
  belongs_to :user, counter_cache: true

  has_many :active_conversations, class_name:  "Conversation",
                                foreign_key: "responder_id"

  has_many :parent, through: :active_conversations, source: :initiator
  has_many :passive_conversations, class_name: "Conversation", foreign_key: "initiator_id"
  has_many :responses, through: :passive_conversations, source: :responder


  validates :body, presence: true

  validates :body, length: { in: 2..140 }

  def time
    "#{created_at.strftime('%r')} on #{created_at.strftime('%x')}"
  end

  def user_pic
    user.pic
  end

  def user_handle
    user.handle
  end

  def user_id
    user.id
  end

  def responses_count
    responses.count
  end

  def parent_id
    if parent.first
      parent.first.id
    else
      nil
    end
  end

  def as_json(_ = nil)
    super(methods: [:time, :user_handle, :user_id, :user_pic, :responses_count, :parent_id])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :thoughts
  has_many :active_relationships, class_name:  "Relationship",
                                foreign_key: "follower_id",
                                dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                               foreign_key: "followed_id",
                               dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_secure_password

  validates :handle, :email, presence: true
  validates :handle, :email, uniqueness: { case_sensitive: false }

  def following_count
    following.count
  end

  def followers_count
    followers.count
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def as_json(_ = nil)
    super(methods: [:following_count, :followers_count])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def signed_in?
    session[:user_id].present?
  end
  helper_method :signed_in? # Make this method available on the view as a helper

  def current_user
    return if session[:user_id].nil?
    @current_user ||= User.find(session[:user_id]) # Return the current_user

  end
  helper_method :current_user # Make this method available on the view as a helper

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #skip_before_action :authenticate_user
  def sign_in
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Username and password do not match"
      render 'sign_in'
    end
  end

  def sign_out
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  def index
    @top_users = User.all.order(thoughts_count: :desc).limit(10)
    @thoughts = Thought.all.order(created_at: :desc)
    respond_to do |format|
      format.html do
        @thoughts
      end
      format.json do
        render json: { thoughts: @thoughts,
                        top_users: @top_users }
      end
    end
  end

  def show
    @thought = Thought.find(params[:id])
    @responses = @thought.responses.order(created_at: :desc)
    respond_to do |format|
      format.html do
      end
      format.json do
        render json: { response: "true", thoughts: @responses }
      end

    end
  end

  def create
    @thought = current_user.thoughts.build(body: params[:body])

    if @thought.save
      if params[:initiator_id]
        Conversation.create(initiator_id: params[:initiator_id],
                            responder_id: @thought.id)
      end
      redirect_to root_path
    else
      flash[:alert] = "Something went wrong! Try again"
      render :new
    end
  end

  def edit
  end

  def destroy
    @thought = Thought.find(params[:id])
    if @thought.destroy
      redirect_to root_path
    else
      flash[:alert] = "Unable to Delete"
      redirect_to(:back)
    end
  end

  private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @thoughts = @user.thoughts.order(created_at: :DESC)
    respond_to do |format|
      format.html do
      end
      format.json do
        render json: { thoughts: @thoughts, user: @user }
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to Chattr!"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Something went wrong! Try again"
      render :new
    end
  end

  def edit
    if signed_in? && params[:id].to_i == current_user.id
      @user = current_user
    else
      redirect_to root_path
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to show_user_path(params[:id])
    else
      render edit
    end
  end
  private

  def user_params
    params.require(:user).permit(:handle, :bio, :email, :password, :password_confirmation, :pic)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper container">
      <%= link_to root_path, class:"brand-logo left" do %>
        <i class="fa fa-comments chattr-logo" aria-hidden="true"></i>
        <small class="chattr-logo"> Chattr</small>
      <% end %>
      <ul class="right">

         <% if signed_in? %>
           <li>
             <%= link_to "Log Out", sign_out_path %>
           </li>
           <li>
             <%= link_to "Hello, @#{current_user.handle}", user_path(current_user.id), class:"welcome-user" %>
           </li>
         <% else %>
           <li>
             <%= link_to "Log In", sign_in_path %>
           </li>
           <li>
             <%= link_to "New User", new_user_path %>
           </li>
         <% end %>
      </ul>

    </div>
  </nav>
</div>

<div class="main-page container">
  <% if signed_in? %>
    <div class="container thought-form-container">
      <%= form_tag '/thoughts', remote:true, class:"new-thought", id:"new-thought", method: :POST do %>
        <div class="row no-margin">
          <div class="col s10 m10 l10">
          <%= text_field_tag :body, nil, class: "user-form", placeholder: "What are you thinking?", autofocus: true %>
          </div>
          <div class="right col s2 m2 l2">
          <%= submit_tag "Share", class: "btn btn-color", id:"thought_submit" %>
          </div>
        </div>

          <small>Characters Remaining: </small><small class="char-count">140</small>

      <% end %>
    </div>
  <% end %>
<%= yield %>
</div>

</body>
</html>

app/views/thoughts/_thoughtbox.html.erb
<div class="col s12 m12 l12 bottom-border">
  <div class="row no-margin">
    <div class="col s6 m4 l4">
        <div class="row no-margin">
          <div class="col s2 m2 l2 profile-pic-center">
            <div class="pic-border">
            <img class="responsive-img circle profile-pic" src="<%= thought.user_pic %>"></div>
          </div>
          <div class="col s7 m7 l7">
            <p><%= link_to "@#{thought.user_handle}", user_path(thought.user_id), class:"link-color" %></p>
          </div>
        </div>
    </div>

    <div class="right link-color pad-right">
      <p> <small><%= thought.time %> </small><br>
          <small>
          <%= link_to "Responses: #{thought.responses_count}", thought_path(thought.id), class:"link-color" %>
          <% if thought.parent_id %>
            <%= link_to " | Context", thought_path(thought.parent_id), class:"link-color"%>
          <% end %></small></p>
    </div>

  </div>
  <%= link_to thought_path(thought.id) do %>
    <div class="row no-margin">
      <div class="col s12 m12 l12">
        <p class="pad-left no-top-margin pad-bot link-color"> <%= thought.body %> </p>
      </div>
    </div>
  <% end %>

</div>

app/views/thoughts/edit.html.erb
<h1>Thoughts#edit</h1>
<p>Find me in app/views/thoughts/edit.html.erb</p>

app/views/thoughts/index.html.erb
<div class="row">
  <div class="col s12 m8 l8 top-thoughts-container" id="thoughts-container">
    <h3 class="container-header"> Now </h3>
    <% @thoughts.each do |thought| %>
      <%= render partial: 'thoughtbox',
          locals: { thought: thought } %>
    <% end %>
  </div>
  <div class= "col s12 m3 l3 top-users-container" id="top-users-container">
    <h3 class="container-header center"> Top Users </h3>

      <% @top_users.each do |user| %>
        <%= render partial: 'users/userbox',
            locals: { user: user } %>
      <% end %>

  </div>
</div>

app/views/thoughts/new.html.erb
<h1>Thoughts#new</h1>
<p>Find me in app/views/thoughts/new.html.erb</p>

app/views/thoughts/show.html.erb
<% if current_user == @thought.user %>
  <%= link_to thought_path(@thought.id), method: :delete do %>
    <div class="btn btn-danger right", id="show-form"> Delete </div>
  <% end %>
<% end %>

<div class="row">
  <div class="col s12 m12 l12 top-thoughts-container"   >
      <%= render partial: 'thoughts/thoughtbox',
          locals: { thought: @thought } %>
  </div>
</div>

<% if signed_in? %>
<div class="btn btn-color right", id="show-form"> Reply </div>

  <div id="form-container" class="hidden-form container thought-form-container">
    <%= form_tag '/thoughts', remote:true, class:"new-thought", id:"new-thought", method: :POST do %>
      <div class="row no-margin">
        <div class="col s10 m10 l10">
        <%= hidden_field_tag :initiator_id, @thought.id %>
        <%= text_field_tag :body, nil, class: "user-form", placeholder: "What are you thinking?", autofocus: true %>
        </div>
        <div class="right col s2 m2 l2">
        <%= submit_tag "Share", class: "btn btn-color", id:"hide-form" %>
        </div>
      </div>

        <small>Characters Remaining: </small><small class="char-count">140</small>

    <% end %>
  </div>
<% end %>

<div class="row">
  <div class="col s12 m12 l12 top-thoughts-container" id="thoughts-container">
      <h3 class="container-header"> Responses </h3>
    <% @responses.each do |thought| %>
      <%= render partial: 'thoughts/thoughtbox',
          locals: { thought: thought } %>
    <% end %>
  </div>
</div>

app/views/users/_userbox.html.erb
<div class="col s12 m12 l12">
  <div class="row">
    <div class="col s2 m2 l2">
      <div class="pic-border">
      <img class="responsive-img circle profile-pic" src="<%= user.pic %>"></div>
    </div>
    <div class="col s7 m7 l7">
      <%= link_to "@#{user.handle}", user_path(user.id), class:"link-color" %><br>
      <small class="link-color">Follows: <%= user.following_count %> | Followers: <%= user.followers_count %></small>
    </div>

    <div class="col s3 m3 l3">
      <p class="chattr-logo"> <i class="fa fa-comment" aria-hidden="true"></i>
        <%= user.thoughts_count %></p>
    </div>
  </div>
</div>

app/views/users/_userboxprofile.html.erb
<div class="col s12 m12 l12">
  <div class="row">
    <div class="col s3 m3 l3 profile-pic-center">
      <div class="pic-border-lg">
      <img class="responsive-img circle profile-pic-lg" src="<%= user.pic %>"></div>
    </div>
    <div class="col s9 m9 l9">
      <div class="row">
        <div class="col s10 m10 l10">
          <h3><%= link_to "@#{user.handle}", user_path(user.id), class:"handle-name link-color" %></h3>
          <h6 class="link-color pad-left">Follows: <%= user.following_count %> | Followers: <%= user.followers_count %></h6>

        </div>

        <div class="col s2 m2 l2">
          <h3 class="chattr-logo"> <i class="fa fa-comment" aria-hidden="true"></i>
            <%= user.thoughts_count %></h3>
        </div>
      </div>
      <div class="row">
        <div class="col s9 m9 l9">
          <p class="pad-left link-color bio-info"> <%= user.bio %> </p>
        </div>
        <div class="col s2 m2 l2">
          <% unless current_user == (@user) %>
            <div id="follow_form">
            <% if current_user.following?(@user) %>
              <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                           html: { method: :delete }) do |f| %>
                <%= f.submit "Unfollow", class: "btn btn-color" %>
              <% end %>
            <% else %>
              <%= form_for(current_user.active_relationships.build) do |f| %>
                <div><%= hidden_field_tag :followed_id, @user.id %></div>
                <%= f.submit "Follow", class: "btn" %>
              <% end %>

            <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <%= form_for(@user, class:"form-group") do |f| %>
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.label :handle%>
    </div>
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.text_field :handle, class:"user-form", autofocus: true%>
    </div>
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.label :bio %>
    </div>
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.text_field :bio, class:"user-form" %>
    </div>
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.label :email %>
    </div>
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.email_field :email, class:"user-form" %>
    </div>
    <!-- <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.label :password %>
    </div>
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.password_field :password, class:"user-form" %>
    </div>
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.label :password_confirmation %>
    </div>
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.password_field :password_confirmation, class:"user-form" %>
    </div> -->
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
      <%= f.submit "Save Changes", class: "btn btn-color" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h3 class="container-header"> Welcome! </h3>


<div class="container">
  <%= form_for(@user, class:"form-group") do |f| %>
    <div class="row">
      <%= f.label :handle%>
    </div>
    <div class="row">
      <%= f.text_field :handle, class:"user-form", autofocus: true%>
    </div>
    <div class="row">
      <%= f.label :email %>
    </div>
    <div class="row">
      <%= f.email_field :email, class:"user-form" %>
    </div>
    <div class="row">
      <%= f.label :password %>
    </div>
    <div class="row">
      <%= f.password_field :password, class:"user-form" %>
    </div>
    <div class="row">
      <%= f.label :password_confirmation %>
    </div>
    <div class="row">
      <%= f.password_field :password_confirmation, class:"user-form" %>
    </div>
    <div class="row">
      <%= f.submit "Sign Up", class: "btn btn-color" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render partial: 'userboxprofile', locals: {user: @user} %>
<% if (signed_in? && params[:id].to_i == current_user.id) || current_user.admin %>
  <div class="btn btn-color right", id="show-form"> Edit Profile </div>

  <div id="form-container" class="container hidden-form">
    <%= form_for(@user, class:"form-group", remote: true) do |f| %>
      <div class="row">
        <%= f.label :handle%>
      </div>
      <div class="row">
        <%= f.text_field :handle, class:"user-form", autofocus: true%>
      </div>
      <div class="row">
        <%= f.label :bio %>
      </div>
      <div class="row">
        <%= f.text_field :bio, class:"user-form" %>
      </div>
      <div class="row">
        <%= f.label :email %>
      </div>
      <div class="row">
        <%= f.email_field :email, class:"user-form" %>
      </div>
      <div class="row">
        <%= f.label :pic %>
      </div>
      <div class="row">
        <%= f.url_field :pic, class:"user-form" %>
      </div>
      <div class="row">
        <%= f.submit "Save Changes", class: "btn btn-color", id: "hide-form" %>
      </div>
    <% end %>
  </div>

<% end %>



<div class="row">
  <div class="col s12 m12 l12 top-thoughts-container" id="thoughts-container">
      <h3 class="container-header"> Now </h3>
    <% @thoughts.each do |thought| %>
      <%= render partial: 'thoughts/thoughtbox',
          locals: { thought: thought } %>
    <% end %>
  </div>
</div>